name: photo_editor_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  flutter_colorpicker: ^1.0.3
  image: ^4.2.0
  path_provider: ^2.0.9
  permission_handler: ^11.3.1
  emoji_picker_flutter: ^3.1.0
  gallery_saver: ^2.3.2
  image_gallery_saver: ^2.0.3
  screenshot: ^3.0.0
  image_editor_plus: ^1.0.6
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  http: ^1.0.0

flutter:
  uses-material-design: true
